# Generated by Django 3.2.7 on 2021-10-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='link',
            field=models.CharField(default=' ', max_length=200, verbose_name='Link'),
        ),
    ]
