# Generated by Django 3.2.7 on 2021-10-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_teachers_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=200, verbose_name='Группы')),
                ('teacher', models.ManyToManyField(to='application.Teachers')),
            ],
        ),
    ]
