# Generated by Django 3.2.7 on 2021-10-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='first_name',
            field=models.CharField(default=' ', max_length=200, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='groups',
            name='last_name',
            field=models.CharField(default=' ', max_length=200, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='groups',
            name='midle_name',
            field=models.CharField(default=' ', max_length=200, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='first_name',
            field=models.CharField(default=' ', max_length=200, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='last_name',
            field=models.CharField(default=' ', max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='midle_name',
            field=models.CharField(default=' ', max_length=200, verbose_name='Отчество'),
        ),
    ]
