# Generated by Django 3.2.7 on 2021-11-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20211028_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='data',
            field=models.CharField(default=' ', max_length=100, verbose_name='Дата'),
        ),
    ]
