# Generated by Django 3.2.7 on 2021-11-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_students_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='data',
        ),
        migrations.AddField(
            model_name='reviews',
            name='data',
            field=models.CharField(default=' ', max_length=100, verbose_name='Дата'),
        ),
    ]
