# Generated by Django 3.2.7 on 2021-11-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20211109_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='id_tg',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
