# Generated by Django 3.2.7 on 2021-12-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_reviews_id_tg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='Communication',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='Freebie',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='Know',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='Overall_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='Teaching_skill',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
