# Generated by Django 3.2.7 on 2021-12-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_reviews_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='data',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
